spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Login
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: database
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: Login
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: StudentMS
        uri: lb://StudentMS
        predicates:
          - Path=/student/**
      - id: TeacherMS
        uri: lb://TeacherMS
        predicates:
          - Path=/teacher/**

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3333/eureka